### PR TITLE
[RFC] TrenchBoot roadmap and ecosystem dependencies

### PR DESCRIPTION
**Pull request by dpsmith**
This WIP roadmap lays out potential features and dependencies across
vendors. Review comments from this PR will be addressed in the next
revision and/or a live discussion.

Signed-off-by: Daniel P. Smith <dpsmith@apertussolutions.com>
Reviewed-by: Piotr Król <piotr.krol@3mdeb.com>

### CODE REVIEW

**Review by pietrushnic — APPROVED** [review]

**Comment by krystian-hebel** [comment]
Typo in "EPYC" (under Yocto). It also lacks a legend or other description. I would also use different wording for the point about fTPM being compliant to PC profile - this does not necessarily imply that it will work with SKINIT.

**Comment by dpsmith** [comment]
Pushed update moving the legend back into the print range and fixing the EPYC typo.

**Review by krystian-hebel — APPROVED** [review]

**Comment by rossphilipson** [comment]
One large task we have talked about in the future is a relaunch driver to allow true late launches to occur at any point. This would be applicable to Intel and AMD hardware.

**Comment by rossphilipson** [comment]
Oh also I noticed emulated SKINIT. There have been discussions here about doing emulated TXT.

**Review by rossphilipson — APPROVED** [review]
I left a few comments but for the most part it looks good to me (at least the parts I am familiar with).

Reviewed-by: Ross Philipson <ross.philipson@oracle.com>

**Comment by dpsmith** [comment]
Updates in latest push,

- colored headers
- fixed more spelling errors
- made every block start with a capital
- separated IPXE and 3mdeb into rows
- added Oracle under LInux KVM
- added QEMU SENTER emulation under Linux KVM
- added QEMU SENTER emulation under Ecosystem & supply chain
- added Kexec preamble under Linux KVM
- added padding on cells so text is not so close to borders
- add top level row show Hardware Space / Software Space
- added a Xen column

**Pull request merged**
